apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-08-02T23:23:46Z"
  generation: 1
  labels:
    run: iotjs-express
  name: iotjs-express
  namespace: default
  resourceVersion: "2228"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/iotjs-express
  uid: 053bc07d-7b0a-4c99-aee8-0239f20f237e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: iotjs-express
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: iotjs-express
    spec:
      containers:
      - image: rzrfreefr/iotjs-express:latest
        imagePullPolicy: Always
        name: iotjs-express
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-02T23:23:49Z"
    lastUpdateTime: "2019-08-02T23:23:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-08-02T23:23:46Z"
    lastUpdateTime: "2019-08-02T23:23:49Z"
    message: ReplicaSet "iotjs-express-77b99d78f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
